# Debugging - see zephyr/sybsys/debug/Kconfig for more options
CONFIG_DEBUG=y
CONFIG_DEBUG_COREDUMP=n
#CONFIG_DEBUG_COREDUMP_BACKEND_LOGGING=n
#CONFIG_DEBUG_COREDUMP_MEMORY_DUMP_MIN=n
CONFIG_SHELL_CMDS_RESIZE=n
CONFIG_DEBUG_INFO=y
CONFIG_EXCEPTION_STACK_TRACE=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_DEBUG_OPTIMIZATIONS=y
