CONFIG_IPC_SERVICE=y
CONFIG_IPC_SERVICE_BACKEND_ICMSG=y
CONFIG_MBOX=y
CONFIG_MBOX_NRFX_IPC=y

CONFIG_LOG=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_RTT_CONSOLE=y

CONFIG_ESB=y

CONFIG_MAIN_STACK_SIZE=2048
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048

CONFIG_HEAP_MEM_POOL_SIZE=2048

# # Enable Partition Manager + flash map when this application is built as a
# # CPUNET child image in the multi-image (MCUboot) build.
# CONFIG_PARTITION_MANAGER_ENABLED=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

CONFIG_SECURE_BOOT=y
# CONFIG_PCD_NET=y