###############################################################
# Logging
###############################################################
# Sadman's note: disabling all logging to remove RTT dependency
CONFIG_LOG=n
#printk is like printf and is not disable-able - use with caution

CONFIG_PRINTK=n
CONFIG_LOG_PRINTK=n
CONFIG_LOG_BUFFER_SIZE=8192
#logging can be in deferred OR immediate mode.  deferred prints in bg thread
CONFIG_LOG_MODE_DEFERRED=n
#CONFIG_LOG_MODE_IMMEDIATE=n   # DOES NOT WORK - turn on immeadiate instead for sys crashes etc.
CONFIG_LOG_INFO_COLOR_GREEN=n
# CONFIG_LOG_BACKEND_RTT=n
CONFIG_LOG_MODE_OVERFLOW=n
# set to zero to disable all logging at compile time
CONFIG_LOG_MAX_LEVEL=0
#network logging
CONFIG_NET_DHCPV4_LOG_LEVEL_ERR=n


#main.c 
CONFIG_MAIN_LOG_LEVEL_INF=n
#storage and configuration logging
CONFIG_FS_LOG_LEVEL_ERR=n
CONFIG_STORAGE_LOG_LEVEL_ERR=n
CONFIG_CFG_LOG_LEVEL_INF=n
#thread logging
CONFIG_WIFI_THREAD_LOG_LEVEL_ERR=n
CONFIG_POWER_THREAD_LOG_LEVEL_ERR=n
CONFIG_MANAGER_THREAD_LOG_LEVEL_ERR=n
CONFIG_LED_THREAD_LOG_LEVEL_ERR=n
#json logging
CONFIG_CFG_JSON_LOG_LEVEL_ERR=n
CONFIG_STATUS_JSON_LOG_LEVEL_ERR=n
CONFIG_FS_SUB_JSON_LOG_LEVEL_ERR=n
CONFIG_REBOOT_JSON_LOG_LEVEL_ERR=n
CONFIG_SYS_PUB_JSON_LOG_LEVEL_ERR=n
CONFIG_WIFI_STATS_PUB_JSON_LOG_LEVEL_ERR=n
CONFIG_REMOTE_PUB_JSON_LOG_LEVEL_ERR=n
#mqtt logging (zephyr stack)
CONFIG_MQTT_LOG_LEVEL_ERR=n
CONFIG_MQTT_HELPER_HELIOGEN_LOG_LEVEL_ERR=n
#mqtt logging (heliogen code)
CONFIG_MQTT_COMMON_LOG_LEVEL_ERR=n
CONFIG_MQTT_TRANSPORT_LOG_LEVEL_ERR=n
CONFIG_TRANSPORT_QUEUE_LOG_LEVEL_ERR=n
CONFIG_REBOOT_MQTT_LOG_LEVEL_ERR=n
CONFIG_STATUS_MQTT_LOG_LEVEL_ERR=n
CONFIG_SYS_PUB_MQTT_LOG_LEVEL_ERR=n
CONFIG_FS_SUB_MQTT_LOG_LEVEL_ERR=n
CONFIG_WIFI_STATS_PUB_MQTT_LOG_LEVEL_ERR=n
CONFIG_REMOTE_PUB_MQTT_LOG_LEVEL_ERR=n
# Sadman's edit
CONFIG_CONTROL_MQTT_LOG_LEVEL_ERR=n
CONFIG_RTT_MQTT_LOG_LEVEL_ERR=n

#CONFIG_TEMPLATE_PUB_MQTT_LOG_LEVEL_ERR=n
#CONFIG_TEMPLATE_SUB_MQTT_LOG_LEVEL_ERR=n
#mcumgr
CONFIG_MCUMGR_LOG_LEVEL_ERR=n
#http update
CONFIG_HTTP_UPDATE_LOG_LEVEL_INF=n
CONFIG_FOTA_DOWNLOAD_LOG_LEVEL_ERR=n
CONFIG_DOWNLOAD_CLIENT_LOG_LEVEL_ERR=n
CONFIG_NET_SOCKETS_LOG_LEVEL_ERR=n
#led logging
CONFIG_LED_PATTERNS_LOG_LEVEL_OFF=n
#watchdog timer
CONFIG_SYS_WDT_LOG_LEVEL_ERR=n
#reset_cause
CONFIG_RESET_CAUSE_LOG_LEVEL_OFF=n
#sys_pub logging
CONFIG_SYS_LOG_LEVEL_ERR=n
#event logging
CONFIG_WIFI_EVENTS_LOG_LEVEL_ERR=n
CONFIG_TRANSPORT_EVENTS_LOG_LEVEL_ERR=n
#wifi statistics logging
CONFIG_WIFI_STATS_LOG_LEVEL_ERR=n
# pubs - publishing scheduler logging
CONFIG_PUBS_LOG_LEVEL_INF=n