# Dependencies for flash storage and MCUBOOT
CONFIG_BOOTLOADER_MCUBOOT=y
#partition manager settings - this says dont put 2ndary image on external flash
#CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=n

#######################################################################
#HTTP download
#######################################################################

#CONFIG_MCUBOOT_SIGNATURE_KEY_FILE="/opt/nordic/ncs/v2.3.0/bootloader/mcuboot/root-rsa-2048.pem"

# Image manager
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_IMG_ERASE_PROGRESSIVELY=y
# FOTA library
CONFIG_FOTA_DOWNLOAD=y
# Download client
CONFIG_DOWNLOAD_CLIENT=y
CONFIG_DOWNLOAD_CLIENT_STACK_SIZE=4096
# DFU Target
CONFIG_DFU_TARGET=y
# Download client for DFU
CONFIG_DOWNLOAD_CLIENT_MAX_FILENAME_SIZE=230
CONFIG_FOTA_DOWNLOAD_PROGRESS_EVT=y

#watchdog
CONFIG_WATCHDOG=y
CONFIG_WDT_LOG_LEVEL_DBG=n
CONFIG_WDT_DISABLE_AT_BOOT=y
CONFIG_TASK_WDT=y
CONFIG_TASK_WDT_MIN_TIMEOUT=10000


CONFIG_DEBUG_THREAD_INFO=n
CONFIG_DEBUG_OPTIMIZATIONS=n
CONFIG_SIZE_OPTIMIZATIONS=y

# # -----------------------------------------------------------------------------
# # nRF5340 multi-image update (APP + NET core)
# # -----------------------------------------------------------------------------
# # Build system output (in build/zephyr) should include:
# #  - app_update.bin
# #  - net_core_app_update.bin
# #
# # Notes:
# # - The actual upload/transport (MCUmgr / custom) is separate from the build.
# # - Requires secondary slot(s) in external flash (see pm_static_*.yml).

# # CONFIG_INCLUDE_NET_CORE_IMAGE=y
# # CONFIG_NRF53_MULTI_IMAGE_UPDATE=y
CONFIG_NRF53_UPGRADE_NETWORK_CORE=y
CONFIG_PCD_APP=y
CONFIG_PM_EXTERNAL_FLASH_MCUBOOT_SECONDARY=y